#!/bin/sh

PORT=$1
CONFIG_FILE=${2:-cfg/at.cfg}
SPEC_DIR=${3:-../spec}

cat > "$CONFIG_FILE" <<EOF
[DEFAULT]
ConnectionType=acceptor
SocketAcceptPort=$PORT
SocketReuseAddress=Y
StartTime=00:00:00
EndTime=00:00:00
SenderCompID=ISLD
ResetOnLogon=Y
FileStorePath=store
[SESSION]
BeginString=FIX.4.0
TargetCompID=TW40
DataDictionary=$SPEC_DIR/FIX40.xml
[SESSION]
BeginString=FIX.4.1
TargetCompID=TW41
DataDictionary=$SPEC_DIR/FIX41.xml
[SESSION]
BeginString=FIX.4.2
TargetCompID=TW42
DataDictionary=$SPEC_DIR/FIX42.xml
[SESSION]
BeginString=FIX.4.3
TargetCompID=TW43
DataDictionary=$SPEC_DIR/FIX43.xml
[SESSION]
BeginString=FIX.4.4
TargetCompID=TW44
DataDictionary=$SPEC_DIR/FIX44.xml
[SESSION]
BeginString=FIXT.1.1
TargetCompID=TW50
DefaultApplVerID=FIX.5.0
TransportDataDictionary=$SPEC_DIR/FIXT11.xml
AppDataDictionary=$SPEC_DIR/FIX50.xml
[SESSION]
BeginString=FIXT.1.1
TargetCompID=TW50SP1
DefaultApplVerID=FIX.5.0SP1
TransportDataDictionary=$SPEC_DIR/FIXT11.xml
AppDataDictionary=$SPEC_DIR/FIX50SP1.xml
[SESSION]
BeginString=FIXT.1.1
TargetCompID=TW50SP2
DefaultApplVerID=FIX.5.0SP2
TransportDataDictionary=$SPEC_DIR/FIXT11.xml
AppDataDictionary=$SPEC_DIR/FIX50SP2.xml
[SESSION]
BeginString=FIX.4.4
TargetCompID=TW
DataDictionary=$SPEC_DIR/FIX44.xml
[SESSION]
BeginString=FIX.4.4
TargetCompID=NO_CHECK_FIELDS_HAVE_VALUES
DataDictionary=$SPEC_DIR/FIX44.xml
ValidateFieldsHaveValues=N
EOF
